### PR TITLE
Update all inputs

### PR DESCRIPTION
**Pull request by balsoft**
Nixpkgs has been repinned. Update stuff.

### CODE REVIEW

**Review by zhenyavinogradov — APPROVED** [review]

**Comment by notgne2** [comment]
If I'm understanding this right, this _MUST_ be updated again before merging, or we'll lose the sudo fix

**Comment by zhenyavinogradov** [comment]
@balsoft Is this good to deploy (after updating again) or is there something else you wanted to do?

**Comment by balsoft** [comment]
This is good (after updating again)

**Comment by zhenyavinogradov** [comment]
I'll deploy it then, so that we don't nixpkgs pinned to a branch anymore

**Comment by zhenyavinogradov** [comment]
Tried updating everything again, but upload-daemon required some changes to the configuration, because its interface changed when we added support for multiple targets, I'll keep the older version for now. I'll deploy tomorrow

**Comment by zhenyavinogradov** [comment]
Deployed

**Pull request merged**
