### PR TITLE
Install copr-cli system-wide

### PR DESCRIPTION
**Pull request by rvem**
Problem: Public buildkite agents now may invoke copr-cli under user that
has access to the publish token. However, we want to be sure that the
path to the copr-cli binary matches the expected one from 'sudoers'.

Solution: Install copr-cli system-wide and use absolute path in
'security.sudo.extraRules'. Absolute path will also be used in the
pipeline configuration.

### CODE REVIEW

**Review by balsoft — APPROVED** [review]
It's probably OK, but I think a better solution is to allow `/run/current-system/sw/bin/copr-cli` and then call it by that absolute path from buildkite. Otherwise there may be strange issues after an update.

**Comment by rvem** [comment]
Do I understand correctly that after `runtimePackages = with pkgs; [ copr-cli ];`, `which copr-cli` will actually say `/run/current-system/sw/bin/copr-cli` and not the path from the `/nix/store`?

**Comment by balsoft** [comment]
No, it will in fact point to the path in `/nix/store` if you do it as-is. What I'm proposing is to install it system-wide, allow the `/run/current-system/sw/bin/copr-cli` in sudo, and then just use `/run/current-system/sw/bin/copr-cli` in buildkite without adding anything to `PATH`.

**Comment by rvem** [comment]
That's makes sense

**Review by balsoft — APPROVED** [review]

**Comment by rvem** [comment]
deployed

**Pull request merged**
