### PR TITLE
Create a dedicate user with copr token access

### PR DESCRIPTION
**Pull request by rvem**
Problem: In order to upload packages to Copr one needs to provide a
config with access token. We'd like to avoid CI having direct access to
it due to security concerns.

Solution: Create a dedicated 'copr-uploader' user that will have the
token in its '$HOME/.config/copr'. Add an ability for the buildkite
agent to do 'sudo -u copr-uploader copr-cli ...'.

Related issue: https://github.com/serokell/tezos-packaging/issues/287

### CODE REVIEW

**Review by balsoft — APPROVED** [review]
Looks alright, but how difficult would it be to just point copr to the secret instead of copying it to the homedir?

**Comment by rvem** [comment]
> how difficult would it be to just point copr to the secret instead of copying it to the homedir?

I was thinking about it as well, `copr-cli` has an option to provide a path to the config with token explicitly, but won't this break an ability to call `sudo -u copr-uploader copr-cli` with arbitrary arguments?

**Comment by rvem** [comment]
deployed

**Comment by balsoft** [comment]
> I was thinking about it as well, copr-cli has an option to provide a path to the config with token explicitly, but won't this break an ability to call sudo -u copr-uploader copr-cli with arbitrary arguments?

You could make a wrapper script that would take only one argument (what you want to upload) and then call `copr-cli` with all the needed wrapper stuff. Probably it's even slightly more secure.

**Pull request merged**
