### PR TITLE
Update nixpkgs

### PR DESCRIPTION
**Pull request by balsoft**
Update nixpkgs to latest repin. Already deployed to albali.

### CODE REVIEW

**Review by zhenyavinogradov — COMMENTED** [review]
There are some errors in CI

**Comment by zhenyavinogradov** [comment]
Btw, do you plan to repin it in all -infra repos, or do you only need it in aquarius-infra?

**Comment by balsoft** [comment]
I only needed it for aquarius-infra to try out github-runner. I might repin in some other repos, but I think @mkaito "wanted" to do it :)

**Review by zhenyavinogradov — APPROVED** [review]
Remember to reboot the instance as well, so that kernel and all those things get updated too

**Pull request merged**
